; General Configuration

[general]
app_name = MiAplicacion
version = 1.0.0
debug = true
att_ponderation=100.0
card_ponderation=100.0
skills_ponderation=120.0
biometrics_ponderation=150.0
normalize_factor=140.0